# Generated by Django 4.2.2 on 2023-11-30 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('cancha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valoracion', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'db_table': 'canchas',
            },
        ),
        migrations.CreateModel(
            name='HorariosCancha',
            fields=[
                ('horarios_cancha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horarios', to='canchas.cancha')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'cancha_horarios',
            },
        ),
        migrations.CreateModel(
            name='CanchaPrecios',
            fields=[
                ('precios_cancha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('fecha_hora_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='precios', to='canchas.cancha')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'precios',
                'db_table': 'cancha_precios',
            },
        ),
    ]
