# Generated by Django 4.2.2 on 2024-02-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
