# Generated by Django 4.2.2 on 2023-10-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_cancha_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios_cancha',
            fields=[
                ('precios_cancha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha_hora_desde', models.DateTimeField()),
                ('cancha_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='canchas.cancha')),
            ],
        ),
    ]
