# Generated by Django 4.2.2 on 2024-02-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_cancha_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/images'),
        ),
    ]
