# Generated by Django 4.2.2 on 2024-01-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_agregar_related_names'),
        ('clases', '0002_agregar_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('inscripcion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inscripcion', models.DateTimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='clases.clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'inscripcion',
                'verbose_name_plural': 'inscripciones',
                'db_table': 'inscripciones',
            },
        ),
    ]
