# Generated by Django 4.2.2 on 2024-01-17 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_hora_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
