# Generated by Django 4.2.2 on 2023-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('domicilio', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'db_table': 'profesores',
            },
        ),
    ]
