# Generated by Django 4.2.2 on 2024-01-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
        ('usuarios', '0002_agregar_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('valoracion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones', to='canchas.cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'valoracion',
                'verbose_name_plural': 'valoraciones',
                'db_table': 'valoraciones',
            },
        ),
    ]
