# Generated by Django 4.2.2 on 2023-11-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cupo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='canchas.cancha')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='HorariosClases',
            fields=[
                ('horarios_clase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horarios', to='clases.clase')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'clase_horarios',
            },
        ),
    ]
