# Generated by Django 4.2.2 on 2024-01-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
        ('canchas', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='profesores.profesor'),
        ),
    ]
