# Generated by Django 4.2.2 on 2024-01-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_agregar_related_names'),
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_reserva', models.DateTimeField()),
                ('estado', models.CharField(choices=[('F', 'Finalizada'), ('P', 'Pendiente'), ('C', 'Cancelada')], default='P', max_length=2)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_hora_cance', models.DateTimeField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='canchas.cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'reservas',
            },
        ),
    ]
