# Generated by Django 4.2.2 on 2023-10-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('cancha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('valoracion', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'db_table': 'canchas',
            },
        ),
    ]
